public enum NamesHumano {
    // Generados con ChatGPT
    Elandra, Shadowheart,
    Thorian, Ironfist,
    Seraphina, Stormrider,
    Garrick, Frostbane,
    Elowen, Silverleaf,
    Cedric, Lightbringer,
    Isolde, Moonshadow,
    Draven, Stormwind,
    Lysandra, Fireheart,
    Kaelan, Starfall,
    Evelina, Skyblade,
    Rowan, Nightshade,
    Finnian, Emberforge,
    Lyria, Swiftarrow,
    Roderick, Stonehelm,
    Elara, Winterthorn,
    Tristan, Dawnbreaker,
    Sylas, Frostwhisper,
    Althea, Starweaver,
    Darian, Shadowstrike,
    Frostbloom,
}
